package users50persec15s.game

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class PlayNewGameUsingLLMServiceTest extends Simulation {

  private val httpProtocol = http
    .baseUrl("http://localhost:8000")
    .inferHtmlResources()
    .acceptHeader("application/json, text/plain, */*")
    .acceptEncodingHeader("gzip, deflate")
    .acceptLanguageHeader("es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3")
    .userAgentHeader("Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0")
  
  private val headers_0 = Map(
  		"Accept" -> "*/*",
  		"Access-Control-Request-Headers" -> "content-type",
  		"Access-Control-Request-Method" -> "POST",
  		"Origin" -> "http://localhost:8081",
  		"Priority" -> "u=4"
  )
  
  private val headers_1 = Map(
  		"Content-Type" -> "application/json",
  		"Origin" -> "http://localhost:8081",
  		"Priority" -> "u=0"
  )
  
  private val headers_3 = Map(
  		"Content-Type" -> "application/json",
  		"Origin" -> "http://localhost:8081"
  )
  
  private val headers_4 = Map(
  		"Accept" -> "image/avif,image/webp,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5",
  		"Priority" -> "u=5, i"
  )
  
  private val headers_6 = Map(
  		"Accept" -> "image/avif,image/webp,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5",
  		"Accept-Encoding" -> "gzip, deflate, br, zstd",
  		"Priority" -> "u=4, i",
  		"Sec-Fetch-Dest" -> "image",
  		"Sec-Fetch-Mode" -> "no-cors",
  		"Sec-Fetch-Site" -> "cross-site"
  )
  
  private val headers_24 = Map("Origin" -> "http://localhost:8081")
  
  private val headers_27 = Map(
  		"Accept" -> "image/avif,image/webp,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5",
  		"Accept-Encoding" -> "gzip, deflate, br, zstd",
  		"Priority" -> "u=5, i",
  		"Sec-Fetch-Dest" -> "image",
  		"Sec-Fetch-Mode" -> "no-cors",
  		"Sec-Fetch-Site" -> "cross-site"
  )
  
  private val headers_40 = Map(
  		"If-None-Match" -> """W/"e7-VjyPpqkA/q6W9O2EYO9xP9LaHQg"""",
  		"Origin" -> "http://localhost:8081"
  )
  
  private val headers_61 = Map(
  		"If-None-Match" -> """W/"f1-rNuqSTa6gF+/XBB6si5bZqifsps"""",
  		"Origin" -> "http://localhost:8081"
  )
  
  private val headers_82 = Map(
  		"If-None-Match" -> """W/"107-nzmLayHOpDf3JHA8KS3LpXtj5C8"""",
  		"Origin" -> "http://localhost:8081"
  )
  
  private val headers_99 = Map(
  		"If-None-Match" -> """W/"101-xDMz/5v8Q+VKsFMf+O/rTUQo0e4"""",
  		"Origin" -> "http://localhost:8081"
  )
  
  private val headers_123 = Map(
  		"If-None-Match" -> """W/"d9-AhPlKgMEWdh5ZQ2+X+eGTYHTLOs"""",
  		"Origin" -> "http://localhost:8081"
  )
  
  private val headers_158 = Map(
  		"If-None-Match" -> """W/"fb-M1WgoWR95AUi5ixoYN0QkcfIYDY"""",
  		"Origin" -> "http://localhost:8081"
  )
  
  private val headers_226 = Map(
  		"If-None-Match" -> """W/"11d-pvYJDXeF/tARWhIDGtzzsybu1ME"""",
  		"Origin" -> "http://localhost:8081"
  )
  
  private val headers_290 = Map(
  		"If-None-Match" -> """W/"12ee-De4LV1IeC1bDOskU0ab8T6GcAkk"""",
  		"Origin" -> "http://localhost:8081",
  		"Priority" -> "u=0"
  )
  
  private val headers_291 = Map(
  		"If-None-Match" -> """W/"88-C9TrvYW1fDXO13j2KBkbLbXd0yk"""",
  		"Origin" -> "http://localhost:8081",
  		"Priority" -> "u=0"
  )
  
  private val uri1 = "commons.wikimedia.org"
  
  private val uri3 = "https://upload.wikimedia.org/wikipedia/commons"

  private val chain_0 =
    exec(
      http("request_0")
        .options("/startGame")
        .headers(headers_0)
        .resources(
          http("request_1")
            .post("/startGame")
            .headers(headers_1)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0001_request.json")),
          http("request_2")
            .options("/configureAssistant")
            .headers(headers_0),
          http("request_3")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0003_request.json")),
          http("request_4")
            .get("http://" + uri1 + "/wiki/Special:FilePath/Dominica%20from%20ISS.jpg")
            .headers(headers_4),
          http("request_5")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0005_request.json")),
          http("request_6")
            .get(uri3 + "/9/90/Dominica_from_ISS.jpg")
            .headers(headers_6),
          http("request_7")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0007_request.json")),
          http("request_8")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0008_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_9")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_10")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0010_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_11")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0011_request.json"))
    )
    .pause(1)
    .exec(
      http("request_12")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0012_request.json"))
    )
    .pause(1)
    .exec(
      http("request_13")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0013_request.json"))
    )
    .pause(1)
    .exec(
      http("request_14")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0014_request.json"))
    )
    .pause(1)
    .exec(
      http("request_15")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_16")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0016_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_17")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0017_request.json"))
    )
    .pause(1)
    .exec(
      http("request_18")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0018_request.json"))
        .resources(
          http("request_19")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0019_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_20")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0020_request.json"))
    )
    .pause(1)
    .exec(
      http("request_21")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_22")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0022_request.json")),
          http("request_23")
            .post("/configureAssistant")
            .headers(headers_1)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0023_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_24")
        .get("/nextQuestion?category=All")
        .headers(headers_24)
        .resources(
          http("request_25")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0025_request.json")),
          http("request_26")
            .get("http://" + uri1 + "/wiki/Special:FilePath/Grand%20Theft%20Auto%2C%20NY%20Chinatown.jpg")
            .headers(headers_4),
          http("request_27")
            .get(uri3 + "/5/5d/Grand_Theft_Auto%2C_NY_Chinatown.jpg")
            .headers(headers_27),
          http("request_28")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0028_request.json")),
          http("request_29")
            .options("/configureAssistant")
            .headers(headers_0),
          http("request_30")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0030_request.json")),
          http("request_31")
            .post("/configureAssistant")
            .headers(headers_1)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0031_request.json"))
        )
    )
    .pause(2)
    .exec(
      http("request_32")
        .get("/nextQuestion?category=All")
        .headers(headers_24)
        .resources(
          http("request_33")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0033_request.json")),
          http("request_34")
            .get("http://" + uri1 + "/wiki/Special:FilePath/Tour%20Advisors.jpg")
            .headers(headers_4),
          http("request_35")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0035_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_36")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0036_request.json"))
    )
    .pause(1)
    .exec(
      http("request_37")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_38")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0038_request.json")),
          http("request_39")
            .post("/configureAssistant")
            .headers(headers_1)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0039_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_40")
        .get("/nextQuestion?category=All")
        .headers(headers_40)
        .resources(
          http("request_41")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0041_request.json")),
          http("request_42")
            .get("http://" + uri1 + "/wiki/Special:FilePath/New%20Audition%201.06.jpg")
            .headers(headers_4),
          http("request_43")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0043_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_44")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0044_request.json"))
    )
    .pause(1)
    .exec(
      http("request_45")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_46")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0046_request.json")),
          http("request_47")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0047_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_48")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0048_request.json"))
    )
    .pause(1)
    .exec(
      http("request_49")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0049_request.json"))
    )
    .pause(1)
    .exec(
      http("request_50")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0050_request.json"))
    )
    .pause(1)
    .exec(
      http("request_51")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_52")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0052_request.json")),
          http("request_53")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0053_request.json")),
          http("request_54")
            .options("/askllm")
            .headers(headers_0),
          http("request_55")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0055_request.json")),
          http("request_56")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0056_request.json")),
          http("request_57")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0057_request.json")),
          http("request_58")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0058_request.json")),
          http("request_59")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0059_request.json")),
          http("request_60")
            .post("/configureAssistant")
            .headers(headers_1)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0060_request.json"))
        )
    )
    .pause(2)
    .exec(
      http("request_61")
        .get("/nextQuestion?category=All")
        .headers(headers_61)
        .resources(
          http("request_62")
            .options("/configureAssistant")
            .headers(headers_0),
          http("request_63")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0063_request.json")),
          http("request_64")
            .get("https://" + uri1 + "/wiki/Special:FilePath/VarvaraMiasnikova.JPG")
            .headers(headers_27)
        )
    )
    .pause(1)
    .exec(
      http("request_65")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0065_request.json"))
    )
    .pause(1)
    .exec(
      http("request_66")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0066_request.json"))
    )
    .pause(1)
    .exec(
      http("request_67")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0067_request.json"))
    )
    .pause(1)
    .exec(
      http("request_68")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_69")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0069_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_70")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0070_request.json"))
    )
    .pause(1)
    .exec(
      http("request_71")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0071_request.json"))
        .resources(
          http("request_72")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0072_request.json")),
          http("request_73")
            .options("/askllm")
            .headers(headers_0),
          http("request_74")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0074_request.json")),
          http("request_75")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0075_request.json")),
          http("request_76")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0076_request.json")),
          http("request_77")
            .options("/configureAssistant")
            .headers(headers_0),
          http("request_78")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0078_request.json")),
          http("request_79")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0079_request.json"))
        )
    )
    .pause(1000.milliseconds)
    .exec(
      http("request_80")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0080_request.json"))
        .resources(
          http("request_81")
            .post("/configureAssistant")
            .headers(headers_1)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0081_request.json"))
        )
    )
    .pause(2)
    .exec(
      http("request_82")
        .get("/nextQuestion?category=All")
        .headers(headers_82)
        .resources(
          http("request_83")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0083_request.json")),
          http("request_84")
            .get("http://" + uri1 + "/wiki/Special:FilePath/OpenTTD-1.11.0-nl.png")
            .headers(headers_4),
          http("request_85")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0085_request.json")),
          http("request_86")
            .get(uri3 + "/0/0d/OpenTTD-1.11.0-nl.png")
            .headers(headers_27),
          http("request_87")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0087_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_88")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0088_request.json"))
    )
    .pause(1)
    .exec(
      http("request_89")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0089_request.json"))
    )
    .pause(1)
    .exec(
      http("request_90")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0090_request.json"))
        .resources(
          http("request_91")
            .options("/askllm")
            .headers(headers_0),
          http("request_92")
            .options("/configureAssistant")
            .headers(headers_0),
          http("request_93")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0093_request.json")),
          http("request_94")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0094_request.json")),
          http("request_95")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0095_request.json")),
          http("request_96")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0096_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_97")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0097_request.json"))
        .resources(
          http("request_98")
            .post("/configureAssistant")
            .headers(headers_1)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0098_request.json"))
        )
    )
    .pause(2)
    .exec(
      http("request_99")
        .get("/nextQuestion?category=All")
        .headers(headers_99)
        .resources(
          http("request_100")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0100_request.json")),
          http("request_101")
            .get("http://" + uri1 + "/wiki/Special:FilePath/Nui%20atoll.jpg")
            .headers(headers_4),
          http("request_102")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0102_request.json")),
          http("request_103")
            .get(uri3 + "/b/b4/Nui_atoll.jpg")
            .headers(headers_27),
          http("request_104")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0104_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_105")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0105_request.json"))
    )
    .pause(1)
    .exec(
      http("request_106")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0106_request.json"))
    )
    .pause(1)
    .exec(
      http("request_107")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0107_request.json"))
    )
    .pause(1)
    .exec(
      http("request_108")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_109")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0109_request.json")),
          http("request_110")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0110_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_111")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0111_request.json"))
    )
    .pause(1)
    .exec(
      http("request_112")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0112_request.json"))
        .resources(
          http("request_113")
            .options("/askllm")
            .headers(headers_0),
          http("request_114")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0114_request.json")),
          http("request_115")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0115_request.json")),
          http("request_116")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0116_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_117")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_118")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0118_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_119")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0119_request.json"))
    )
    .pause(1)
    .exec(
      http("request_120")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0120_request.json"))
        .resources(
          http("request_121")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0121_request.json")),
          http("request_122")
            .post("/configureAssistant")
            .headers(headers_1)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0122_request.json"))
        )
    )
    .pause(2)
    .exec(
      http("request_123")
        .get("/nextQuestion?category=All")
        .headers(headers_123)
        .resources(
          http("request_124")
            .options("/configureAssistant")
            .headers(headers_0),
          http("request_125")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0125_request.json")),
          http("request_126")
            .get("http://" + uri1 + "/wiki/Special:FilePath/Mauritius%2023.08.2009%2011-42-31.jpg")
            .headers(headers_4)
        )
    )
    .pause(1)
    .exec(
      http("request_127")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0127_request.json"))
        .resources(
          http("request_128")
            .get(uri3 + "/9/96/Mauritius_23.08.2009_11-42-31.jpg")
            .headers(headers_27),
          http("request_129")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0129_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_130")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0130_request.json"))
    )
    .pause(1)
    .exec(
      http("request_131")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_132")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0132_request.json")),
          http("request_133")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0133_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_134")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0134_request.json"))
    )
    .pause(1)
  
  private val chain_1 =
    exec(
      http("request_135")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0135_request.json"))
    )
    .pause(1)
    .exec(
      http("request_136")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0136_request.json"))
        .resources(
          http("request_137")
            .options("/askllm")
            .headers(headers_0),
          http("request_138")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0138_request.json")),
          http("request_139")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0139_request.json")),
          http("request_140")
            .options("/configureAssistant")
            .headers(headers_0),
          http("request_141")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0141_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_142")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0142_request.json"))
    )
    .pause(1)
    .exec(
      http("request_143")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0143_request.json"))
    )
    .pause(1)
    .exec(
      http("request_144")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0144_request.json"))
    )
    .pause(1)
    .exec(
      http("request_145")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0145_request.json"))
    )
    .pause(1)
    .exec(
      http("request_146")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_147")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0147_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_148")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0148_request.json"))
    )
    .pause(1)
    .exec(
      http("request_149")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0149_request.json"))
        .resources(
          http("request_150")
            .options("/askllm")
            .headers(headers_0),
          http("request_151")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0151_request.json")),
          http("request_152")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0152_request.json")),
          http("request_153")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0153_request.json")),
          http("request_154")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0154_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_155")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_156")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0156_request.json")),
          http("request_157")
            .post("/configureAssistant")
            .headers(headers_1)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0157_request.json"))
        )
    )
    .pause(2)
    .exec(
      http("request_158")
        .get("/nextQuestion?category=All")
        .headers(headers_158)
        .resources(
          http("request_159")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0159_request.json")),
          http("request_160")
            .get("http://" + uri1 + "/wiki/Special:FilePath/GloriaDicksonLadyofBurlesquecropped.jpg")
            .headers(headers_4),
          http("request_161")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0161_request.json")),
          http("request_162")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0162_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_163")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_164")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0164_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_165")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0165_request.json"))
    )
    .pause(1)
    .exec(
      http("request_166")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0166_request.json"))
    )
    .pause(1)
    .exec(
      http("request_167")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0167_request.json"))
        .resources(
          http("request_168")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0168_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_169")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_170")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0170_request.json")),
          http("request_171")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0171_request.json")),
          http("request_172")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0172_request.json")),
          http("request_173")
            .options("/askllm")
            .headers(headers_0),
          http("request_174")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0174_request.json")),
          http("request_175")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0175_request.json")),
          http("request_176")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0176_request.json")),
          http("request_177")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0177_request.json"))
        )
    )
    .pause(1000.milliseconds)
    .exec(
      http("request_178")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_179")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0179_request.json")),
          http("request_180")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0180_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_181")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0181_request.json"))
    )
    .pause(1)
    .exec(
      http("request_182")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0182_request.json"))
    )
    .pause(1)
    .exec(
      http("request_183")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0183_request.json"))
        .resources(
          http("request_184")
            .options("/configureAssistant")
            .headers(headers_0),
          http("request_185")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0185_request.json")),
          http("request_186")
            .options("/askllm")
            .headers(headers_0),
          http("request_187")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0187_request.json")),
          http("request_188")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0188_request.json")),
          http("request_189")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0189_request.json"))
        )
    )
    .pause(1000.milliseconds)
    .exec(
      http("request_190")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0190_request.json"))
    )
    .pause(1)
    .exec(
      http("request_191")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0191_request.json"))
        .resources(
          http("request_192")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0192_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_193")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_194")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0194_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_195")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0195_request.json"))
    )
    .pause(1)
    .exec(
      http("request_196")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0196_request.json"))
    )
    .pause(1)
    .exec(
      http("request_197")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0197_request.json"))
    )
    .pause(1)
    .exec(
      http("request_198")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0198_request.json"))
    )
    .pause(1)
    .exec(
      http("request_199")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_200")
            .options("/askllm")
            .headers(headers_0),
          http("request_201")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0201_request.json")),
          http("request_202")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0202_request.json")),
          http("request_203")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0203_request.json")),
          http("request_204")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0204_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_205")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0205_request.json"))
    )
    .pause(1000.milliseconds)
    .exec(
      http("request_206")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0206_request.json"))
    )
    .pause(1)
    .exec(
      http("request_207")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0207_request.json"))
    )
    .pause(1)
    .exec(
      http("request_208")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_209")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0209_request.json")),
          http("request_210")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0210_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_211")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0211_request.json"))
    )
    .pause(1)
    .exec(
      http("request_212")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0212_request.json"))
        .resources(
          http("request_213")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0213_request.json")),
          http("request_214")
            .options("/askllm")
            .headers(headers_0),
          http("request_215")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0215_request.json")),
          http("request_216")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0216_request.json")),
          http("request_217")
            .options("/configureAssistant")
            .headers(headers_0),
          http("request_218")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0218_request.json")),
          http("request_219")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0219_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_220")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0220_request.json"))
    )
    .pause(1)
    .exec(
      http("request_221")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0221_request.json"))
    )
    .pause(1)
    .exec(
      http("request_222")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0222_request.json"))
    )
    .pause(1)
    .exec(
      http("request_223")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_224")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0224_request.json")),
          http("request_225")
            .post("/configureAssistant")
            .headers(headers_1)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0225_request.json"))
        )
    )
    .pause(2)
    .exec(
      http("request_226")
        .get("/nextQuestion?category=All")
        .headers(headers_226)
        .resources(
          http("request_227")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0227_request.json")),
          http("request_228")
            .get("http://" + uri1 + "/wiki/Special:FilePath/Pe%C3%B1afiel%20PM%2017939.jpg")
            .headers(headers_4),
          http("request_229")
            .get(uri3 + "/3/30/Pe%C3%B1afiel_PM_17939.jpg")
            .headers(headers_27),
          http("request_230")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0230_request.json")),
          http("request_231")
            .options("/configureAssistant")
            .headers(headers_0),
          http("request_232")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0232_request.json")),
          http("request_233")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0233_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_234")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0234_request.json"))
        .resources(
          http("request_235")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0235_request.json")),
          http("request_236")
            .options("/askllm")
            .headers(headers_0),
          http("request_237")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0237_request.json")),
          http("request_238")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0238_request.json")),
          http("request_239")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0239_request.json"))
        )
    )
    .pause(1000.milliseconds)
    .exec(
      http("request_240")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_241")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0241_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_242")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0242_request.json"))
    )
    .pause(1)
    .exec(
      http("request_243")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0243_request.json"))
    )
    .pause(1)
    .exec(
      http("request_244")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0244_request.json"))
    )
    .pause(1)
    .exec(
      http("request_245")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0245_request.json"))
        .resources(
          http("request_246")
            .options("/configureAssistant")
            .headers(headers_0),
          http("request_247")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0247_request.json")),
          http("request_248")
            .options("/askllm")
            .headers(headers_0),
          http("request_249")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0249_request.json")),
          http("request_250")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0250_request.json")),
          http("request_251")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0251_request.json")),
          http("request_252")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0252_request.json")),
          http("request_253")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0253_request.json")),
          http("request_254")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0254_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_255")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_256")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0256_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_257")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0257_request.json"))
    )
    .pause(1)
    .exec(
      http("request_258")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0258_request.json"))
    )
    .pause(1)
    .exec(
      http("request_259")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0259_request.json"))
    )
    .pause(1)
    .exec(
      http("request_260")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0260_request.json"))
    )
    .pause(1)
  
  private val chain_2 =
    exec(
      http("request_261")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_262")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0262_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_263")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0263_request.json"))
    )
    .pause(1)
    .exec(
      http("request_264")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0264_request.json"))
    )
    .pause(1)
    .exec(
      http("request_265")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0265_request.json"))
    )
    .pause(1)
    .exec(
      http("request_266")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0266_request.json"))
    )
    .pause(1)
    .exec(
      http("request_267")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_268")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0268_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_269")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0269_request.json"))
    )
    .pause(1)
    .exec(
      http("request_270")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0270_request.json"))
    )
    .pause(1)
    .exec(
      http("request_271")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0271_request.json"))
    )
    .pause(1)
    .exec(
      http("request_272")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0272_request.json"))
    )
    .pause(1)
    .exec(
      http("request_273")
        .options("/configureAssistant")
        .headers(headers_0)
        .resources(
          http("request_274")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0274_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_275")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0275_request.json"))
    )
    .pause(1)
    .exec(
      http("request_276")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0276_request.json"))
    )
    .pause(1)
    .exec(
      http("request_277")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0277_request.json"))
    )
    .pause(1)
    .exec(
      http("request_278")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0278_request.json"))
        .resources(
          http("request_279")
            .options("/askllm")
            .headers(headers_0),
          http("request_280")
            .options("/configureAssistant")
            .headers(headers_0),
          http("request_281")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0281_request.json")),
          http("request_282")
            .post("/askllm")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0282_request.json")),
          http("request_283")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0283_request.json")),
          http("request_284")
            .post("/configureAssistant")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0284_request.json"))
        )
    )
    .pause(1000.milliseconds)
    .exec(
      http("request_285")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0285_request.json"))
    )
    .pause(1)
    .exec(
      http("request_286")
        .post("/configureAssistant")
        .headers(headers_3)
        .body(RawFileBody("game/playnewgameusingllmservicetest/0286_request.json"))
        .resources(
          http("request_287")
            .post("/configureAssistant")
            .headers(headers_1)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0287_request.json"))
        )
    )
    .pause(2)
    .exec(
      http("request_288")
        .options("/save-session")
        .headers(headers_0)
        .resources(
          http("request_289")
            .post("/save-session")
            .headers(headers_3)
            .body(RawFileBody("game/playnewgameusingllmservicetest/0289_request.json"))
        )
    )
    .pause(1)
    .exec(
      http("request_290")
        .get("/get-user-sessions/gatling")
        .headers(headers_290)
        .resources(
          http("request_291")
            .get("/get-users-totaldatas")
            .headers(headers_291)
        )
    )
  
  private val scn = scenario("PlayNewGameUsingLLMServiceTest")
    .exec(chain_0, chain_1, chain_2)

	setUp(scn.inject(constantUsersPerSec(50).during(15))).protocols(httpProtocol)
}
