services:
  mongodb:
    container_name: mongodb-wichat_es1b
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  authservice:
    container_name: authservice-wichat_es1b
    image: ghcr.io/arquisoft/wichat_es1b/authservice:latest
    profiles: ["dev", "prod"]
    build: ./users/authservice
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  sessionservice:
    container_name: sessionservice-wichat_es1b
    image: ghcr.io/arquisoft/wichat_es1b/sessionservice:latest
    profiles: ["dev", "prod"]
    build: ./users/sesionservice
    depends_on:
      - mongodb
    ports:
      - "8005:8005"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  userservice:
    container_name: userservice-wichat_es1b
    image: ghcr.io/arquisoft/wichat_es1b/userservice:latest
    profiles: ["dev", "prod"]
    build: ./users/userservice
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  llmservice:
    container_name: llmservice-wichat_es1b
    image: ghcr.io/arquisoft/wichat_es1b/llmservice:latest
    profiles: ["dev", "prod"]
    build: ./llmservice
    ports:
      - "8003:8003"
    networks:
      - mynetwork

  questionservice:
    container_name: questionservice-wichat_es1b
    image: ghcr.io/arquisoft/wichat_es1b/questionservice:latest
    profiles: ["dev", "prod"]
    build: ./questionservice
    depends_on:
      - mongodb
    ports:
      - "8004:8004"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
      MONGODB_URI_QUESTIONS: mongodb://mongodb:27017/questionsDb

  gatewayservice:
    container_name: gatewayservice-wichat_es1b
    image: ghcr.io/arquisoft/wichat_es1b/gatewayservice:latest
    profiles: ["dev", "prod"]
    build: ./gatewayservice
    depends_on:
      - mongodb
      - userservice
      - authservice
      - llmservice
      - questionservice
      - sessionservice
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      LLM_SERVICE_URL: http://llmservice:8003
      QUESTION_SERVICE_URL: http://questionservice:8004
      SESSION_SERVICE_URL: http://sessionservice:8005

  apiservice:
    container_name: apiservice-wichat_es1b
    image: ghcr.io/arquisoft/wichat_es1b/apiservice:latest
    profiles: [ "dev", "prod" ]
    build: ./apiservice
    depends_on:
      - gatewayservice
    ports:
      - "8015:8015"
    networks:
      - mynetwork


  prometheus:
    image: ghcr.io/arquisoft/wichat_es1b/prometheus:latest
    container_name: prometheus-wichat_es1b
    profiles: [ "dev", "prod" ]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - ./gatewayservice/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - gatewayservice


  grafana:
    image: ghcr.io/arquisoft/wichat_es1b/grafana:latest
    container_name: grafana-wichat_es1b
    profiles: [ "dev", "prod" ]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./gatewayservice/monitoring/grafana/dashboards:/etc/grafana/dashboards
      - ./gatewayservice/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_DASHBOARDS=/etc/grafana/dashboards
    ports:
      - "9091:9091"
    depends_on:
      - prometheus


  webapp:
    container_name: webapp-wichat_es1b
    image: ghcr.io/arquisoft/wichat_es1b/webapp:latest
    profiles: ["dev", "prod"]
    build: 
      context: ./webapp
      args:
        LLM_API_KEY: ${LLM_API_KEY}
    depends_on:
      - gatewayservice
    ports:
      - "3000:3000"

      



volumes:
  mongodb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge
